basic:
  output_dir: output
  seed: 0
  use_swanlab: false
  use_tensorboard: true
  use_wandb: false
  train_version: 0
  ddim: 50

loss:
  global_lc : true
  consistency: l1
  lamb_sparse: 1
  sparse: l1
  use_target_action: true

model:
  structure: "ca"
  hidden_dim: 512  # dp
  attn_heads: 8    # d_head = 512 / 8 = 64
  dim_feedforward: 1024
  block_encoder_type: "SA"

pruning:
  target_prune_ratio: 0.80

training:
  early_stop: true
  epochs: 45
  lr: 0.0001
  min_lr: 1.0e-06

  optimizer:
    betas:
    - 0.9
    - 0.999
    weight_decay:
      bias_no_decay: 0.0
      embeddings: 1.0e-06
      mlp_head: 1.0e-05
      obs_encoder: 0.0001
      transformer: 0.001

  patience: 30
  warmup_steps: 4

stage2:
  lr : 1.0e-04
  lr_min : 1.0e-06
  num_batch_train_tra: 7      # 
  num_batch_val_tra: 1        # 
  train_tra_batch_size: 16    # batch size
  val_tra_batch_size: 16    # batch size
  epochs_tra: 20      # epochs
  init_bias: 0.0

visual:
  save_gate_animation: false
